### ISSUE TITLE
Vulners API auto-throttling

### ISSUE THREAD

**Issue by vulnersCom** [google/minions#17]
Hey-ho!
We've faced some kind of issues with projects using our API.
Like trying to make a 1000rps to our backend using our official Python API :)
So I've made auto-throttling mechanics using two HTTP headers at the backend and some kind of semaphore in the Python API acting on them.
In response from the backend you can see:
X-Vulners-Ratelimit-Reqlimit = This headers tells client about ratelimit. Float.
X-Vulners-Ratelimit-Rate = This headers tells client his current rate. Float.
So avoiding banhammer is quite easy - just respect this values and throttle down if the end is near :)

I've added [throttling functionality in this commit](https://github.com/vulnersCom/api/commit/edf0fed70203caddddfb4e6136bf8d5351ebba85).
May I suggest you to follow it in Go lib? It's not urgent, but a definitely good stuff :)

**Comment by paradoxengine** [comment]
That makes sense.
Given that Resty does not support the feature natively. I think I can get away with just using a Ticker (https://github.com/golang/go/wiki/RateLimiting) and wrapping the existing calls, given I expect you don't want more than tens of queries per seconds.

What's a decent good default to start with for the cases where APIs are there and where they are not?
Dynamic update should not be hard but I might want to experiment with a default first since it's the first time I use channel ;-)

**Comment by vulnersCom** [comment]
Hmmm.
"This works well for rates up to tens of operations per second. For higher rates, prefer a token bucket rate limiter" this sounds like a correct way, no?
We do want :) Especially at the scanning API's entry points when we are scanning thousand of machines.
Limit is usually between 50-500rps.
I've set as 'default' value 10rps for any entry point.
Then, after first call to the API I'm looking is there a ratelimit header or not.
If it is -> This is a new ratelimit for this entry point.

**Comment by paradoxengine** [comment]
I ended implementing it using a proper rate limiter rather than the Ticker logic.
I've set 5 rqs with a burst of 10 if you don't have an API, 10 with a burst of 20 if you do: is that too much as a starter?

Now implementing the dynamic limits, feel free to comment on the CLs

**Comment by vulnersCom** [comment]
Almost fine 👍 
Awesome!
